### ISSUE TITLE
Criar listagem dos pacientes

### ISSUE THREAD

**Issue by Lucianocljr** [ifpe-cti/saudegaranhuns#10]
Que tem como finalidade demonstrar todos os pacientes cadastrados, para realizar as operações após o atendimento. 
Característica da função:
- Posicionar botões ao lado de cada item, botões esses de Alterar e Deletar.
- Quando o item for clicado duas vezes, redirecionar para outra página e mostra o item detalhadamente.

**Comment by fabriciofx** [comment]
@Lucianocljr Quem vai cuidar desta funcionalidade? Você?

**Comment by Lucianocljr** [comment]
Sim, cuidarei desta funcionalidade. No tocante a elaboração da tela de listagem.

**Comment by fabriciofx** [comment]
Closed by #53.
