### ISSUE TITLE
Remover redundância nos classes de conexão Hibernates

### ISSUE THREAD

**Issue by HeriklesVinicyus** [ifpe-cti/saudegaranhuns#100]
Com as novas atualizações no Hibernate as classes de conexão do projeto estão fazendo verificações desnecessárias.

eu vou corrigir isso.

**Comment by fabriciofx** [comment]
@HeriklesVinicyus Que verificações? Seja mais específico.

**Comment by HeriklesVinicyus** [comment]
Issue não necessário
