### ISSUE TITLE
Alteração dos controllers de todas as telas da inteface Web

### ISSUE THREAD

**Issue by Igor201** [ifpe-cti/saudegaranhuns#101]
Fazer Adição dos controllers que faltam @Igor201

Eu vou adicionar

**Comment by fabriciofx** [comment]
@Igor201 Seja mais específico quando você escrever a issue. Quais controllers faltam? O que eles devem fazer?

**Comment by fabriciofx** [comment]
@Igor201 *POR FAVOR*, você poderia ser *mais específico* sobre o que está fazendo no título da issue, no corpo da issue e no título dos seus commits?

**Comment by fabriciofx** [comment]
@Igor201 Continuou a mesma coisa. Pense primeiro o que você quer fazer e depois explique direito. Não tenha medo de gastar linhas. Pode gastar. O importante é que fique claro o que você quer fazer. Depois altere o título da issue para também ficar melhor explicado.

**Comment by Igor201** [comment]
Alteração dos controllers Paciente/Posto/Atendente
para se aplicar as páginas Web, auxiliando issue #31

**Comment by fabriciofx** [comment]
@Igor201 Favor alterar o título da issue para explicar melhor a mudança que você quer fazer.
