### ISSUE TITLE
Exclusão da pasta de teste br.edu.ifpe.garanhuns.recursos

### ISSUE THREAD

**Issue by jjunio01** [ifpe-cti/saudegaranhuns#103]
Com a inclusão do Spring Boot ao projeto, os serviços Rest do software serão testados utilizando o plugin `Postman` do Google Chrome, tornando assim desnecessário manter os arquivos existente nesta pasta vinculados ao projeto.

**Comment by jjunio01** [comment]
Obs.

Implementarei o solicitado nesta issue #103

**Comment by fabriciofx** [comment]
@jjunio01 Como assim? Não entendi. Os testes fazem parte do código da aplicação e devem estar na mesma base. Você quer separá-los? É isso?

**Comment by jjunio01** [comment]
@fabriciofx  Esses arquivos são gerados pela NetBeans para construção de uma página .`xhtml `onde é possível executar as requisições HTTP, porém com o Spring Boot a estrutura que gera está página não faz mais parte do projeto, sendo assim não temos como efetuar os teste desta maneira por isso os arquivos serão excluídos eles eram apenas auxiliares ao teste e não o teste.

Obs. O teste dos serviços serão efetuados em outra issue a qual irei abrir.

**Comment by fabriciofx** [comment]
@jjunio01 Ok então. Vá em frente!

**Comment by fabriciofx** [comment]
Closed by #104.
