### ISSUE TITLE
Alterar a documentação para utilizar o maven-wrapper

### ISSUE THREAD

**Issue by fabriciofx** [ifpe-cti/saudegaranhuns#108]
A documentação está refletindo a utilização do ` mvn` ao invés do `mvnw` e precisa ser alterada.

**Comment by fabriciofx** [comment]
Closed by #130.

**Comment by jofernando** [comment]
@fabriciofx no arquivo `README`, no tópico de `Como contribuir` no 8º passo ainda está utilizando o `mvn`.
