### ISSUE TITLE
Implementar a ação para que o atendente indique o status do atendimento

### ISSUE THREAD

**Issue by lsoaresesilva** [ifpe-cti/saudegaranhuns#114]
O atendente visualizará a listagem das consultas do dia e poderá modificar o status do atendimento do dia:

1. Devem ter dois botões: atendido e cancelado.
2. A consulta irá sumir da listagem principal
3. Alterar o status do modelo no BD

**Comment by jofernando** [comment]
@lsoaresesilva alterar tag para @jofernando.

**Comment by fabriciofx** [comment]
Closed by #167.
