### ISSUE TITLE
Criar o menu superior para o administrador

### ISSUE THREAD

**Issue by lsoaresesilva** [ifpe-cti/saudegaranhuns#117]
O menu deve conter:

* CRUD Posto
* CRUD Atendente

**Comment by fabriciofx** [comment]
@lsoaresesilva Favor assinalar (label) de quem deverá realizar esta tarefa.

**Comment by jofernando** [comment]
@Igor201 quando criar o menu coloca o nome do arquivo de `menu.xhtml` dentro de uma pasta chamada `admin` (que tu irá criar).

**Comment by fabriciofx** [comment]
Closed by #186.
