### ISSUE TITLE
Gerenciar o direcionamento após o login dos usuários

### ISSUE THREAD

**Issue by lsoaresesilva** [ifpe-cti/saudegaranhuns#118]
Deve adicionar o usuário na Session.

Deve verificar o perfil do usuário e redirecionar para a tela correspondente.

Deve-se criar um LoginFilter para filtrar as requisições.

**Comment by jofernando** [comment]
@lsoaresesilva alterar tag para @jofernando.

**Comment by fabriciofx** [comment]
Closed by #181.
