### ISSUE TITLE
Problema com o Jacoco

### ISSUE THREAD

**Issue by Lucianocljr** [ifpe-cti/saudegaranhuns#12]
@fabriciofx na hora que vou compilar o código o jacoco está lançando uma exceção e não estou conseguindo resolver. Cliquei em um link que mostra no erro, li, e essa situação ocorre em virtude de um plugin.

**Comment by fabriciofx** [comment]
@Lucianocljr Coloca aqui a mensagem de erro...

**Comment by HeriklesVinicyus** [comment]
@Lucianocljr e @fabriciofx  o jacoco está exigindo os 80% dos testes, por isso não está construindo.

**Comment by fabriciofx** [comment]
@Lucianocljr Suspendi a verificação de cobertura do jacoco. Sincronize a sua base com o upstream e veja se consegue construir corretamente. Se ainda sim der erro, favor colocar a mensagem de erro.

**Comment by Lucianocljr** [comment]
@fabriciofx sincronizei a base de dados. Bom, construindo está, porém, quando abre o navegador da erro. "HTTP Status 404 - Página não encontrada"

**Comment by fabriciofx** [comment]
@Lucianocljr Aí é *outro* problema, certo? Se sim, feche esta issue e abra outra.

Além do mais, eu acho que isso não é problema do código do master e sim da sua base. Tem que ver o código e as configurações que você está fazendo...

**Comment by Lucianocljr** [comment]
Realmente @fabriciofx o problema do Jacoco foi solucionado. Segunda - feira (06/11/2017) vejo com o professor @lsoaresesilva este problema.
