### ISSUE TITLE
Corrigir exceção lançada no PostoSaudeHibernate

### ISSUE THREAD

**Issue by jofernando** [ifpe-cti/saudegaranhuns#125]
Lançando exceção `NullPointerException` no métodos de `buscarPorNome`

**Comment by jofernando** [comment]
@HeriklesVinicyus

**Comment by fabriciofx** [comment]
@jofernando O PR corrigiu esse bug? Se sim, fechar a issue.

**Comment by jofernando** [comment]
Closed by #126
