### ISSUE TITLE
Exclusão do atributo endereço do Paciente

### ISSUE THREAD

**Issue by jjunio01** [ifpe-cti/saudegaranhuns#128]
@HeriklesVinicyus(Model) , @Igor201(View), @jjunio01(Rest), Excluir o atributo endereço da classe Paciente, para simplificar a aplicação e por não haver mais a necessidade desta vinculação conforme combinado.

**Comment by Igor201** [comment]
exclusão feita nas telas de cadastro WEB.

**Comment by HeriklesVinicyus** [comment]
@jjunio01 , @lsoaresesilva , @Igor201 para que eu possa submeter minha alterações, Junio precisa altera o Rest, pois ele usa métodos no model.

**Comment by jjunio01** [comment]
@HeriklesVinicyus, haverá alteração no nome dos métodos ou da classe?


O que exatamente devo alterar.

**Comment by HeriklesVinicyus** [comment]
linha 49 "Endereco enderecoPaciente = paciente.getEndereco();" do arquivo "br.edu.ifpe.garanhuns.sg.recursosPacientesResource". endereço não existirá mais.

**Comment by jjunio01** [comment]
@HeriklesVinicyus Estou trabalhando na issue #107, quando submeter o PR irei excluir as linhas solicitadas.

**Comment by jjunio01** [comment]
@HeriklesVinicyus PR submetido.
