### ISSUE TITLE
Adicionar o drive de conexão JDBC do MySQL 

### ISSUE THREAD

**Issue by HeriklesVinicyus** [ifpe-cti/saudegaranhuns#13]
@fabriciofx o senhor poderia adicionar no projeto o Driver do JDBC MySQL, assim ficará logo no projeto geral.

**Comment by fabriciofx** [comment]
@HeriklesVinicyus done, conforme o commit 23899fd17dd4a952b969f592b1af2537fe6cc8d5. Se concordar com as mudanças, não esqueça de fechar a issue.

**Comment by fabriciofx** [comment]
@HeriklesVinicyus Ainda tá confundindo *drive* com *driver*, aspira?

**Comment by HeriklesVinicyus** [comment]
@fabriciofx concordo com as mudanças, mas não entendi a minha confusão!

**Comment by HeriklesVinicyus** [comment]
@fabriciofx  vi onde errei.
