### ISSUE TITLE
Erro ao recuperar consultas por paciente.

### ISSUE THREAD

**Issue by jjunio01** [ifpe-cti/saudegaranhuns#131]
@HeriklesVinicyus Na consulta do serviço Rest utilizando o Postman o retorno é null e é lançada a seguinte exceção:

`Falha ao recuperar os Pacientes por nome. Erro: javax.persistence.EntityNotFound                                          Exception: No row with the given identifier exists: [br.edu.ifpe.garanhuns.sg.mo                                          del.PostoSaude#1]`

Causa da exceção: `ConsultaHibernate` linha `121`.

**Comment by HeriklesVinicyus** [comment]
@jjunio01 ok!

**Comment by jjunio01** [comment]
Resolvido #131
