### ISSUE TITLE
Criar mocks das telas do dispositivo mobile

### ISSUE THREAD

**Issue by lsoaresesilva** [ifpe-cti/saudegaranhuns#14]
Fazer o esboço das telas de cadastro de paciente, agendamento de consulta e listagem de consultas agendadas. Utilizar a ferramenta https://moqups.com/

TODO: adicionar para @jofernando

**Comment by fabriciofx** [comment]
@lsoaresesilva Adicionei para ele via labels. Assim, se ele quiser saber quais as issues estão assinaladas para ele, ele pode filtrar por este label.

**Comment by fabriciofx** [comment]
@lsoaresesilva Esta ferramenta [moqups](https://moqups.com), gera algum arquivo? Ele é binário? Ele pode ser adicionado à base de código? Ele pode ser aberto/lido por outro programa ou somente on-line?

**Comment by lsoaresesilva** [comment]
@fabriciofx é online, vou ver se há algo integrado ao Github

**Comment by lsoaresesilva** [comment]
@jofernando fazer as telas de cadastro de paciente, cadastro de consulta e listagem de consultas seguindo o que foi discutido em sala. No cadastro de consulta considerar o campo observação, prioridade (idoso, deficiente físico, gestante, bebê de colo) e especialidade (dentista e outros).
