### ISSUE TITLE
Erro ao recuperar Paciente por nome

### ISSUE THREAD

**Issue by jjunio01** [ifpe-cti/saudegaranhuns#144]
@HeriklesVinicyus Deve ser corrigido a Query para consulta de pacientes por nome, pois está lançando a seguinte exceção.

 `Erro: javax.persistence.EntityNotFoundException: No row with the given identifier exists: [br.edu.ifpe.garanhuns.sg.model.PostoSaude#1]`

**Comment by lsoaresesilva** [comment]
@HeriklesVinicyus vai que é tua

**Comment by HeriklesVinicyus** [comment]
@jjunio01 me mostre o código que você está executando

**Comment by HeriklesVinicyus** [comment]
@jjunio01, @lsoaresesilva, @fabriciofx, @jofernando, @Lucianocljr, @Igor201 ! todas as vezes que o model for alterado o banco precisa ser recriado, a linha  <property name="hbm2ddl.auto"></property> do arquivo hibernate.cfg precisa ser alterada para _create_ para recriar o banco, após isso a mesma poderá ser _update_.

**Comment by jjunio01** [comment]
@HeriklesVinicyus Foi falha minha que não lembrei dessa alteração no `hibernate.cfg`

**Comment by jjunio01** [comment]
Ciente.
