### ISSUE TITLE
Resolver exceção ao salvar Paciente

### ISSUE THREAD

**Issue by jjunio01** [ifpe-cti/saudegaranhuns#145]
Ao tentar salvar paciente são lançadas as seguintes exceções: 
`Falha ao salvar Paciente. Erro: java.lang.IllegalStateException: org.hibernate.TransientObjectException: object references an unsaved transient instance - save the transient instance before flushing: br.edu.ifpe.garanhuns.sg.model.Endereco`

`Falha ao salvar Bairro. Erro: org.hibernate.exception.ConstraintViolationException: could not execute statement`

`ERROR 10188 --- [nio-8080-exec-8] o.h.engine.jdbc.spi.SqlExceptionHelper   : Duplicate entry 'login' for key 'UK_g1orfqvgih1w8s3vyg15fq2b8'`

**Comment by lsoaresesilva** [comment]
@HeriklesVinicyus  Possível solução: https://stackoverflow.com/questions/2302802/object-references-an-unsaved-transient-instance-save-the-transient-instance-be

**Comment by jjunio01** [comment]
Problema resolvido,
Closed by #145
