### ISSUE TITLE
Gerar SQL para geração de relatórios

### ISSUE THREAD

**Issue by lsoaresesilva** [ifpe-cti/saudegaranhuns#148]
Deve ser gerado uma lista para indicar o total de atendimentos (consultas com o status atendido) de um determinado posto por meses.

Exemplo: Todos os atendimentos do posto de heliópolis de 01/10/2017 à 01/12/2017.

Deve ser gerado uma lista para representar **todos os atendimentos** (consultas com o status atendido) **de todos os postos** em um período de data. 

Exemplo: Todos os atendimentos dos postos de 01/10/2017 à 01/12/2017.

**Comment by HeriklesVinicyus** [comment]
@lsoaresesilva para melhor flexibilidade iri criar os métodos com a assinaturas: gerarRelatorioConsultaPorStatus(Status status); e gerarRelatorioConsultaPorPostoStatus(PostoSaude posto, Status status);

**Comment by fabriciofx** [comment]
Closed by #187 .
