### ISSUE TITLE
Vincular membros do projeto ao projeto

### ISSUE THREAD

**Issue by lsoaresesilva** [ifpe-cti/saudegaranhuns#15]
@fabriciofx  não estou conseguindo vincular issues aos demais alunos, eles precisam ser adicionados ao projeto como colaboradores, correto?

**Comment by fabriciofx** [comment]
@lsoaresesilva Certo. O problema de se fazer isso é que eles vão ter acesso a fazer push direto na master do repositório original (upstream). Minha recomendação é **não** colocar eles como colaboradores e criar labels para cada um (exemplo: @fulano). Assim, você fica sabendo que aquela issue está associada a determinada pessoa e de quebra pode filtrar e fazer outras coisas.

**Comment by fabriciofx** [comment]
@lsoaresesilva Vou criar as labels para eles aí você analisa, certo?

**Comment by lsoaresesilva** [comment]
Beleza, valeu

**Comment by fabriciofx** [comment]
@lsoaresesilva Se você concorda e aceita a solução, deve fechar a issue. Lembre-se só quem abre a issue é que deve fechá-la.
