### ISSUE TITLE
Utilizar a versão embedded do tomcat

### ISSUE THREAD

**Issue by fabriciofx** [ifpe-cti/saudegaranhuns#16]
Desenvolver aplicações web e ainda mais testá-las é mais difícil utilizando uma versão standalone do que uma versão embedded. Assim, a minha sugestão é utilizar a versão embedded do tomcat nesta aplicação de modo que a mesma seja self-contained, não precisando de mais nada além do que ela mesma para executar. Isto pode ser verificado neste [link](https://devcenter.heroku.com/articles/create-a-java-web-application-using-embedded-tomcat). Eu vou cuidar disso.

**Comment by lsoaresesilva** [comment]
Já ouviu falar do Jetty? Mais rápido e leve que o Tomcat:

https://www.eclipse.org/jetty/documentation/9.4.x/jetty-maven-plugin.html

**Comment by fabriciofx** [comment]
@lsoaresesilva Eu conheço o Jetty sim, mas pensei em usar algo que o team já estivesse mais familiarizado. Analisando, as nossas opções são:
- Tomcat embedded
- Jetty
- Wildfly embedded
- Takes

Eu particularmente prefiro o [Takes](http://www.takes.org), mas se não me engano, ele não suporta JSF (que eu também sou contra, mas como disse antes, tenho que pensar no team).

Mas vou analisar as outras opções. Fazendo uns testes rápidos, o tomcat embedded até que está bem rapidinho... 😄

**Comment by fabriciofx** [comment]
Foi adicionado além do Tomcat embedded o [SpringBoot](https://projects.spring.io/spring-boot/). Closed by #85.
