### ISSUE TITLE
Utilizar o maven-wrapper para não precisar de um maven pré-instalado

### ISSUE THREAD

**Issue by fabriciofx** [ifpe-cti/saudegaranhuns#17]
Um dos problemas de se utilizar o [maven](http://maven.apache.org) é que para construir a aplicação é preciso que ele seja pré-instalado no sistema. Ainda assim, ele também é uma dependência, uma vez que até a versão diferente do maven usado na construção pode afetar o processo de construção do software. Para resolver esse problema temos duas soluções:
1. Utilizar uma imagem [docker](https://www.docker.com) com o maven pré-instalado
2. Utilizar o [maven-wrapper](https://github.com/takari/maven-wrapper)

O maven-wrapper é uma solução mais simples para este problema. O que ele faz é apenas colocar uma versão do maven *embedded* ao seu projeto. Assim, para construir a aplicação deve-se utilizar o comando ```$ ./mvnw``` ao invés do ```$ mvn```. Para instalar o maven-wrapper, utilizamos o [Takari Maven Plugin](https://github.com/takari/takari-maven-plugin), utilizando o comando:
```shell
$ mvn -N io.takari:maven:wrapper
```
Portanto, a instalação e utilização do mesmo é simples e recomendo utilizá-lo. Eu cuidarei dessa issue.

**Comment by fabriciofx** [comment]
Closed #18 .

**Comment by lsoaresesilva** [comment]
@fabriciofx vai com calma nos plugins e outras ferramentas, é bom primeiro apresentar aos alunos e que eles utilizem antes de vincular ao projeto, pode confundi-los.

**Comment by fabriciofx** [comment]
@lsoaresesilva A ferramenta é a mesma, no caso o maven. A diferença é que se a pessoa quiser instalar o maven e usar via linha de comando ela pode ou ela pode usar um maven "embutido".

**Comment by lsoaresesilva** [comment]
@fabriciofx então, é somente para apresentar aos alunos primeiro, de preferência em sala, explicar e depois mandar para o projeto, se não eles podem ficar confusos...

**Comment by fabriciofx** [comment]
@lsoaresesilva Mas não muda nada. Eles podem usar o maven como sempre. É um opcional.

**Comment by fabriciofx** [comment]
Closed by #18.
