### ISSUE TITLE
Alterar Valores do enum DiasSemana 

### ISSUE THREAD

**Issue by HeriklesVinicyus** [ifpe-cti/saudegaranhuns#174]
É necessário  alterar os valores dos dias da semana e colocar a "SEGUNDA" como o primeiro dia e o "Domingo" como sétimo dia, essa alteração se torna importante para o algorítimo automático que gera as datas para as consultas (#35) devido a forma que a classe LocalDate trabalha os dias da semana.

@lsoaresesilva , @fabriciofx , @jofernando , @jjunio01 , @FenandoSMedeiros , @Igor201, por favor! verificar o que isso afetará no trabalho de vocês.

@HeriklesVinicyus quem fará isso

**Comment by fabriciofx** [comment]
Closed by #175.
