### ISSUE TITLE
Corrigir menu de administrador e atendente

### ISSUE THREAD

**Issue by jofernando** [ifpe-cti/saudegaranhuns#195]
@Igor201 o menu de administrador está dando erro, as tags `menuitem`, `submenu` e `menubar` tem que estar dentro de um `<h:form></h:form>`.
Também substituir as tags html `<head></head>` e `<body></body>` pelas jsf `<h:head></h:head>`, `<h:body></h:body>`

**Comment by jofernando** [comment]
Obs.: o botão de logout não funcionar, alterar action do botão de logout de `"#{loginUsuarioController.logout()}"` para `"#{loginUsuarioController.realizarLogout()}"`. Também colocar um update com o valor `@form` para que quando o logout for realizado atualizar o menu.

**Comment by jofernando** [comment]
O mesmo ocorre no menu de atendente, por favor corrigir.

**Comment by jofernando** [comment]
Atendente não tem acesso a listagem de consulta, sendo que a listagem é somente a listagem de consultas do paciente logado. Por favor retirar do menu.

**Comment by fabriciofx** [comment]
Closed by #209 .
