### ISSUE TITLE
Limpar formulário das páginas de cadastro

### ISSUE THREAD

**Issue by jofernando** [ifpe-cti/saudegaranhuns#196]
@Igor201 as página de cadastro de paciente, atendente e posto não limpam os formulários. Exemplo: quando cadastro um paciente e recarrego a página para cadastrar outro os dados anteriores ainda estão lá, quando não deveriam. Sendo assim recomendo que tu crie um método no controlador de cada classe para limpar os dados e na página tu o chame antes da página ser renderizada com o seguinte método `<f:event listener="#{teuController.teuMetodoLimpar()}" type="preRenderView"/>`, pode colocar este método entre o `head` e o `body`.

**Comment by fabriciofx** [comment]
Closed by #210 .
