### ISSUE TITLE
Gerenciar redirecionamento após ação ser executada

### ISSUE THREAD

**Issue by jofernando** [ifpe-cti/saudegaranhuns#197]
@Igor201 
* Após cadastrar/alterar paciente, posto e atendente ele não me redireciona para lugar nenhum, o correto seria redirecionar para a devida página de listagem do mesmo ou então atualizar a página para limpar o formulário. Escolher qual dessas opções irá escolher.
* Após realizar login atualizar a página para que o menu seja atualizado.
* Corrigir botão cancelar nas páginas. Ele não está redirecionando corretamente, alterar de `commandButton` para `button` e colocar no `href` o seguinte padrão `/pasta/pagina.xhtml` caso a página esteja dentro de alguma pasta ou simplesmente `/pagina.xhtml` caso a página esteja na raiz.

**Comment by fabriciofx** [comment]
Closed by #216.
