### ISSUE TITLE
Remoção da classe NewClass

### ISSUE THREAD

**Issue by HeriklesVinicyus** [ifpe-cti/saudegaranhuns#198]
Devido a vários conflitos de construção que estão ocorrendo por conta desse classe, vou remove-la.
Quando for aceitar esse PR lembrar de aceitar primeiro o outro que esta aberto e onde existe o newClass, pois se for aceita depois não delas irá gerar outro conflito para o sistema.

**Comment by HeriklesVinicyus** [comment]
Quando for aceitar esse PR lembrar de aceitar primeiro o outro que esta aberto e anda tem o newClass!

**Comment by fabriciofx** [comment]
Closed by #199 .
