### ISSUE TITLE
Erro no agendamentoAutomaticoConsulta

### ISSUE THREAD

**Issue by HeriklesVinicyus** [ifpe-cti/saudegaranhuns#206]
Ao realizar criar o testes da classe ConsultaHibernate verifiquei que os Dias da semana que o algoritmo retorna é uma dia da semana a mais (Ex: dia=QUARTA ele retorna um dia=SEXTA), sei que o erro está no método _recuperarHorarioAtendimentoPorPostoSaudeEspecialidade(PostoSaude ps, Especialidade especialidade)_ e sei como resolver.
eu resolverei.

**Comment by fabriciofx** [comment]
@HeriklesVinicyus Se você sabe como resolver, porque não resolve? Envie seu PR. 😄

**Comment by HeriklesVinicyus** [comment]
sou eu que vou fazer, mas não tenho que abri uma issue???

**Comment by HeriklesVinicyus** [comment]
Melhor assim?

**Comment by fabriciofx** [comment]
@HeriklesVinicyus Você disse que sabe como resolver mas não disse que **ia** resolver. Entendeu a diferença?

**Comment by fabriciofx** [comment]
Closed by #208.
