### ISSUE TITLE
Erro no agendamentoAutomaticoConsulta(PostoSaude posto, Especialidade especialidade)

### ISSUE THREAD

**Issue by HeriklesVinicyus** [ifpe-cti/saudegaranhuns#212]
O método _agendamentoAutomaticoConsulta(PostoSaude posto, Especialidade especialidade)_ está com um erro semântico  na linha 265 da classe _ConsultaHibernate_ :
```Java
if (consultas.size() <= horariosAtandimento.get(i).getQuantidade()) 
```
deveria ser: 
```Java
if (consultas.size() < horariosAtandimento.get(i).getQuantidade())
```

eu vou resolver.

**Comment by fabriciofx** [comment]
Closed by #213.
