### ISSUE TITLE
Levantamento de informações

### ISSUE THREAD

**Issue by fabriciofx** [ifpe-cti/saudegaranhuns#3]
No Google Drive havia um documento chamado "Anotações" com os questionamentos abaixo. O correto é que estes questionamentos fossem uma issue no projeto. Assim, as movi para esta issue e vou assiná-la para @lsoaresesilva.

### Deve-se investigar as seguintes informações:

1. Como funciona a ordem de prioridade da fila de atendimento?
2. Como funciona o direcionamento do paciente para o posto a partir do seu endereço?
3. Todos os postos tem acesso a Internet?

**Comment by lsoaresesilva** [comment]
Beleza
