### ISSUE TITLE
Criar algoritmo de agendamento automático da consulta

### ISSUE THREAD

**Issue by lsoaresesilva** [ifpe-cti/saudegaranhuns#35]
* Considerar dias de atendimento, a quantidade no dia e o posto de saúde.

**Comment by HeriklesVinicyus** [comment]
@lsoaresesilva teria com o senhor explicar um pouco mais!

**Comment by lsoaresesilva** [comment]
@HeriklesVinicyus quando um paciente solicita um atendimento deve ser verificado em seu posto qual o dia mais próximo disponível. Para isto deve ser verificado quais os dias de atendimento da especialidade solicitada, a quantidade disponível por dia, e quais solicitações já existem até o momento. Quando o total de solicitações exceder um determinado dia, então as demais consultas são jogadas para o próximo dia disponível. 

Verificar as classes Atendimento e HorarioAtendimento em [!alt](https://github.com/ifpe-cti/saudegaranhuns/blob/master/diagrama_classe.png)

**Comment by HeriklesVinicyus** [comment]
@lsoaresesilva ! [algoritmo](https://github.com/HeriklesVinicyus/saudegaranhuns/commit/c1313cdf9448d27e62dfa8586f3bc7ddf72fa85c) pronto conforme a UML, porém quando estava implementando o código me fiz a seguinte pergunta "como entra a questão do horários em consulta?", pois como na classe consulta não tem um atributo para isso não dá para implementar baseado em horários , e se for adicionado qual o retorno disso para as views? (web e mobile)

**Comment by fabriciofx** [comment]
Closed by #174 .
