### ISSUE TITLE
Criar ação no DAO pra alterar o status da consulta

### ISSUE THREAD

**Issue by lsoaresesilva** [ifpe-cti/saudegaranhuns#37]

**Comment by HeriklesVinicyus** [comment]
@lsoaresesilva o senhor poderia definir melhor esse issue.

**Comment by lsoaresesilva** [comment]
@HeriklesVinicyus Quando um paciente é atendido no posto o atendente informa isto no sistema e o resultado é uma indicação que o estado da consulta alterou. Como armazenamos o estado em um status, então o status deve ser atualizado para o novo.
