### ISSUE TITLE
Corrigir nome e e-mail do autor na configuração do Git

### ISSUE THREAD

**Issue by fabriciofx** [ifpe-cti/saudegaranhuns#57]
Prezados @HeriklesVinicyus @Igor201 @Lucianocljr @lsoaresesilva @jjunio01 @jofernando @fernandomedeiros, gostaria de solicitar a vocês que prestassem atenção na configuração do Git, pois estou vendo pelos logs/blame que está aparecendo só o primeiro nome, "apelido" ou coisa do gênero no lugar do nome ou e-mail do autor do commit. Minha recomendação é que utilize como nome **pelo menos** o seu primeiro e último nome. Lembrando para configurar no Git, é preciso na máquina em questão, digitar:
```bash
$ git config --global user.name "Primeiro Último"
$ git config --global user.email "seu-email@dominio.com"
```

**Comment by fabriciofx** [comment]
@fernandomedeiros @lsoaresesilva @HeriklesVinicyus @Igor201 @jjunio01 @jofernando Vocês atentaram para isto? Não vou aceitar mais commits cujo nome do autor não esteja mais corretamente configurado!

**Comment by HeriklesVinicyus** [comment]
O git não deixa o dá o commit se user e o email não estiverem configurado


________________________________
De: Fabricio Cabral <notifications@github.com>
Enviado: terça-feira, 28 de novembro de 2017 14:19:57
Para: ifpe-cti/saudegaranhuns
Cc: HeriklesVinicyus; Mention
Assunto: Re: [ifpe-cti/saudegaranhuns] Corrigir nome e e-mail do autor na configuração do Git (#57)


@FernandoMedeiros<https://github.com/fernandomedeiros> @lsoaresesilva<https://github.com/lsoaresesilva> @HeriklesVinicyus<https://github.com/heriklesvinicyus> @Igor201<https://github.com/igor201> @jjunio01<https://github.com/jjunio01> @jofernando<https://github.com/jofernando> Vocês atentaram para isto? Não vou aceitar mais commits cujo nome do autor não esteja mais corretamente configurado!

**Comment by fabriciofx** [comment]
@HeriklesVinicyus O problema é **como** vocês estão configurando o Git. Coloca como nome de usuaário *Igor201* ou *Junio* não acrescenta muita coisa, certo? Lembre-se que este sistema fará parte do seu portfólio de trabalhos no futuro. Como saber se foi você que contribuiu se você não coloca o nome e e-mail corretos?

**Comment by HeriklesVinicyus** [comment]
@fabriciofx o senhor poderia fechar esse issue?!?!
