### ISSUE TITLE
Refatorar localização e nome das páginas JSF

### ISSUE THREAD

**Issue by fabriciofx** [ifpe-cti/saudegaranhuns#58]
@Igor201 O nome das páginas JSF estão ruins e precisam ser refatorados. Exemplo: onde se tem `CadastroPostoSaudeForm.xhtml` minha recomendação é que se crie uma pasta chamada `posto` e nela coloque como nome `cadastro.xhtml`. Note também que página JSF não é classe e portanto em seu nome não deve ter a notação camel case.

**Comment by Igor201** [comment]
Compreendido, irei fazer as alterações

**Comment by fabriciofx** [comment]
Closed by #86.
