### ISSUE TITLE
Refatorar a localização das imagens

### ISSUE THREAD

**Issue by fabriciofx** [ifpe-cti/saudegaranhuns#59]
@jjunio01 No diretório `src/main/webapp` estão localizados pequenas imagens. Estas devem ser refatoradas para colocar numa pasta para elas. Se alguma parte do sistema precisa da localização destes arquivos, esta parte também deve ser reconfigurada para a nova localização dos aquivos.

**Comment by jjunio01** [comment]
@fabriciofx , as imagens localizadas na pasta mencionada assim como os arquivos test-services.html, test-resbeans.js e arquivos .css, servem apenas para testar a execução dos serviços Rest.
Após a integração e testes de todos os serviços Rest os arquivos serão excluídos do projeto.

**Comment by fabriciofx** [comment]
@jjunio01 Se estes arquivos são **gerados** eles não deviam ser rastreados no projeto. Se são relativos a testes deveriam estar na pasta `src/tests`. Favor excluí-los do projeto e do rastreamento.

**Comment by fabriciofx** [comment]
@jjunio01 O que fez com que estas imagens fossem geradas? É algum teste? Se sim, ao executar novamente este teste, as imagens serão geradas novamente?

**Comment by fabriciofx** [comment]
Closed by #93.
