### ISSUE TITLE
POJO de Paciente.

### ISSUE THREAD

**Issue by HeriklesVinicyus** [ifpe-cti/saudegaranhuns#6]
Realizações da atividade do quadro "a fazer", criação do POJO de paciente e atendente. Sprint - 06/11/17

**Comment by fabriciofx** [comment]
@HeriklesVinicyus Favor não colocar datas no título das issues, pois elas não fazem sentido. Além do mais, note que essa issue cobre duas funcionalidades. O correto, ao meu ver, seria **uma** funcionalidade por issue. Assim, favor quebrar esta issue em duas.

**Comment by HeriklesVinicyus** [comment]
fecho aquela e crio outras duas ou como faço ?
a date era referente a o Sprint .

**Comment by fabriciofx** [comment]
@HeriklesVinicyus Você muda apenas o título dela e cria outra. Não precisa de data no título. Quando você abre uma issue ela já tem data de abertura.

**Comment by fabriciofx** [comment]
@HeriklesVinicyus Tira a data do título rapaz.

**Comment by HeriklesVinicyus** [comment]
@fabriciofx essa data não é a atual e a da data entrega do sprint.

**Comment by fabriciofx** [comment]
@HeriklesVinicyus Então coloque ela no corpo da issue e não no título. Quando você for ver os logs e o histórico das issues, essa data aí no título não fará o menor sentido.

**Comment by HeriklesVinicyus** [comment]
@fabriciofx pergunta! toda vez que eu for fazer uma(mínima) alteração no código tenho que abrir uma issue?
exemplo: se eu for criar os pojos, adicionar o hibernateUtil e os daos, tenho que cria uma issue para cada um desse?

**Comment by fabriciofx** [comment]
@HeriklesVinicyus Não. O que você quer fazer é "Adicionar suporte ao Paciente" e adicionar todas as classes relativas ao Paciente; "Adicionar suporte ao Hibernate" e adicionar todas as classes para ativar o Hibernate. Veja a issue como uma tarefa a ser realizada. Essa tarefa pode ter vários passos. Os passos você registra via commits, mas só há uma issue.

**Comment by HeriklesVinicyus** [comment]
Issue já incrementada no projeto.
