### ISSUE TITLE
Duplicidade na geração de commits no origin

### ISSUE THREAD

**Issue by jjunio01** [ifpe-cti/saudegaranhuns#60]
@fabriciofx Estou necessitando de ajuda para sincronizar o upstream com o origin. Fiz diversas tentativas de sincronizar as bases após os merges dos PR com o upstream ontem (27/11/2017). 

Meu origin hoje apresenta diversos commits "repetidos" porém não existe a necessidade de mantê-los vinculados ao meu origin.

Segue alguns dos commits:

commit 1a35ed5fcdf7e719ea24cdd9bac4175a1f99663e
Author: Junio <junio.araujo01@yahoo.com>
Date:   Tue Nov 21 20:55:03 2017 -0300

    Exclusão do recurso de Consulta do master

commit 6a92929a79cdd6161edc1f6120602c44e10aa785
Author: Junio <junio.araujo01@yahoo.com>
Date:   Tue Nov 21 20:51:03 2017 -0300

    Adicionado recurso Consulta

commit f1654f0892cf44e489eeb2fc878633e50637b711
Author: Junio <junio.araujo01@yahoo.com>
Date:   Tue Nov 21 20:55:03 2017 -0300

    Exclusão do recurso de Consulta do master

commit 45fec7b8a8575426c7849ffbf3d0c8811d6c19c0
Author: Junio <junio.araujo01@yahoo.com>
Date:   Tue Nov 21 20:51:03 2017 -0300

    Adicionado recurso Consulta

commit ab2a6619c1affe1ba4c55cc81ce1ca4f48840569
Author: Junio <junio.araujo01@yahoo.com>
Date:   Tue Nov 21 20:55:03 2017 -0300

    Exclusão do recurso de Consulta do master

commit e2fb5b6f7b3da61e718f3e89fe81cccf09dad311
Author: Junio <junio.araujo01@yahoo.com>
Date:   Tue Nov 21 20:51:03 2017 -0300

    Adicionado recurso Consulta

commit 6e0e4ef3ddc19334e3d09ff0938ea7a59350af92
Author: Junio <junio.araujo01@yahoo.com>
Date:   Tue Nov 21 20:55:03 2017 -0300

    Exclusão do recurso de Consulta do master

commit 265646444a1779cddc9fbf229b98968f7d8d9ce6
Author: Junio <junio.araujo01@yahoo.com>
Date:   Tue Nov 21 20:51:03 2017 -0300

    Adicionado recurso Consulta

commit 2666c88c6f4caa01f35410e1a8261f9cb5f67d63
Author: Junio <junio.araujo01@yahoo.com>
Date:   Tue Nov 21 20:55:03 2017 -0300

    Exclusão do recurso de Consulta do master

...

Gostaria de orientação para retirar os commits repetidos do meu origin.

**Comment by fabriciofx** [comment]
@jjunio01 Estes commits não aparecem no master do upstream. Este problema está relacionado à sua base local apenas. Não faço a menor ideia do que aconteceu aí. **Nunca** vi tal problema acontecer. Minha sugestão mais fácil e simples: renomeie o seu projeto local para outro nome, faça um novo clone do upstream, faça um push dos branches que você tem no projeto antigo e depois faça um fetch para o projeto novo. Caso não dê certo, dá uma pesquisada na net como resolve isso...

**Comment by jjunio01** [comment]
Não consegui fazer o PUSH dos branchers remotos. O comando não deveria ser o PULL, para "puxar" as modificações do branch remoto para minha maquina local ?

**Comment by fabriciofx** [comment]
@jjunio01 Se os seus branches já estão no remoto, você faz um FECTH. Se eles não estão ainda, você deve fazer um PUSH e depois um FETCH. Se você não está conseguindo fazer um PUSH, qual a mensagem de erro que ele dá?

**Comment by jjunio01** [comment]
Mensagem de erro:

$ git push origin 26
error: src refspec 26 does not match any.
error: failed to push some refs to 'https://jjunio01@github.com/ifpe-cti/saudegaranhuns.git'

**Comment by jjunio01** [comment]
Com o FETCH ele não encontra a referencia remota.

Mensagem de erro: "$ git fetch origin 26
fatal: Couldn't find remote ref 26
"

Configuração dos repositórios remotos:

$ git remote -v
origin  https://jjunio01@github.com/ifpe-cti/saudegaranhuns.git (fetch)
origin  https://jjunio01@github.com/ifpe-cti/saudegaranhuns.git (push)
upstream        https://github.com/ifpe-cti/saudegaranhuns.git (fetch)
upstream        https://github.com/ifpe-cti/saudegaranhuns.git (push)

**Comment by jjunio01** [comment]
@fabriciofx  Verifiquei que a referência para o meu origin estava diferente, corrigi e consegui fazer o primeiro FETCH

**Comment by jjunio01** [comment]
@fabriciofx , na minha maquina local, agora tenho todos os branch criados no projeto antigo, sendo que o meu master está sincronizado com o upstream.

Agora está faltando enviar o meu master local para o origin, sem fazer merge de códigos, pois quero que meu repositório remoto esteja igual ao meu local. Como faço?

**Comment by fabriciofx** [comment]
@jjunio01 Você pode apagar o seu repositório remoto e refazer o fork. Mas lembre-se que ao fazê-lo você perderá todos os branches remotos enviados (mas se você os tiver localmente, não há problema).

**Comment by jjunio01** [comment]
@fabriciofx  Problema resolvido.

Obrigado.

**Comment by jjunio01** [comment]
Closed by #60
