### ISSUE TITLE
Melhorar a criação de modelos UML

### ISSUE THREAD

**Issue by fabriciofx** [ifpe-cti/saudegaranhuns#7]
Hoje em dia temos uma pasta que guarda os modelos UML na forma de figura. Esta forma não é aconselhada, pois não temos o arquivo que gerou este diagrama muito menos podemos versioná-lo. Assim, é interessante criar uma forma de criar e versionar estes diagramas. Recomendo para isto utilizar o [PlantUML](http://plantuml.com/) e adicionar [este](https://github.com/jeluard/maven-plantuml-plugin) plugin do maven para "compilar" estes diagramas em imagens. Eu cuidarei dessa tarefa.

**Comment by lsoaresesilva** [comment]
Na realidade já utilizamos um aplicativo online chamado Draw.io. Não realiza esta mudança ainda, pois irei avaliar esta sugestão que você indicou, pois não a conheço.

**Comment by fabriciofx** [comment]
@lsoaresesilva Dá para versionar os arquivos criados pelo Draw.io? Além disso, perceba que tudo fica centralizado na própria base. O ideal, sempre, é que tudo fique centralizado o máximo possível e que possa ser versionado pelo git. E utilizar o PlantUML não é difícil. Uma lida rápida no [guia](http://plantuml.com/class-diagram) dele já é o suficiente para entender como ele funciona.

**Comment by fabriciofx** [comment]
@lsoaresesilva E aí? Decidiu sobre os diagramas gerados pelo [PlantUML](http://www.plantuml.com)? Viu no [README.md](https://github.com/ifpe-cti/saudegaranhuns/blob/master/README.md) como fica? Dá uma olhada no arquivo [saudegaranhuns-classes.uml](https://github.com/ifpe-cti/saudegaranhuns/blob/master/docs/uml/saudegaranhuns-classes.uml) para você ver como é a sintaxe. É muito simples e semelhante a código Java.

**Comment by fabriciofx** [comment]
@lsoaresesilva Ok. Closed by #8.
