### ISSUE TITLE
Alterar retorno dos métodos que fazem a persistência no banco de dados

### ISSUE THREAD

**Issue by jofernando** [ifpe-cti/saudegaranhuns#79]
@HeriklesVinicyus alterar o retorno  dos métodos que são void para o tipo de retorno boolean, como por exemplos os métodos de inserir e atualizar.

**Comment by fabriciofx** [comment]
@jofernando Qual a razão dessa mudança?

**Comment by jofernando** [comment]
@fabriciofx sem essa mudança não tem como mostrar uma mensagem para o usuário avisando se sua ação foi ou não bem sucedida.
Exemplo: digamos que o usuário está tentando cadastrar uma consulta. No controller chamo o método cadastrar do model, se me retornar true aviso que o cadastro foi feito com sucesso, caso retorne false aviso que não foi realizado o cadastro.

**Comment by jofernando** [comment]
@fabriciofx ok, digamos que lá no model lançou uma exceção (claro que com uma mensagem amigavel), o usuário não tem noção do erro? Até porque as exceções são lançadas no console, certo? O usuário vai ter acesso a algum tipo de console?

**Comment by fabriciofx** [comment]
@jofernando Depende do que você quer dizer por *erro*. O que é um erro para você? Digamos que ao tentar salvar um cadastro, não tem conexão com o SGBD. Isto é um erro e a mensagem a ser enviada ao usuário não precisa ser de uma forma que ele vá entender, porque a ideia é que ele acione o suporte e mande essa mensagem para eles. Agora, se você está se referindo a uma consulta que não retornou nada, precisa ver se era esperado que esta consulta não retornasse nenhum dado. Exemplo: você faz uma consulta para saber se um determinado paciente já se consultou em um determinado posto de saúde. É esperado que não retorne nada, se o paciente não se consultou no posto. Isto *não* é um erro. Não retornar nada é um resultado esperado.

**Comment by jofernando** [comment]
@fabriciofx certo, então continua do jeito que está.
