### ISSUE TITLE
Arquivos JSF com problemas de namespace ou de módulos

### ISSUE THREAD

**Issue by fabriciofx** [ifpe-cti/saudegaranhuns#84]
@Lucianocljr Detectei que vários arquivos JSF desenvolvidos por você `listar-*.xhtml` e outros estão com problemas no namespace ou que estão faltando módulos. Favor corrigi-los.

**Comment by lsoaresesilva** [comment]
@Lucianocljr Alterar, para que a issue seja aceita:

* modificar o title das páginas jsf que estão sendo enviadas para indicar a operação que está sendo feita. Exemplo: Listagem de pacientes.
* Criar o controlador e modificar os nomes das variáveis para refletir as informações reais.
