### ISSUE TITLE
Alterar o property:"hbm2ddl.auto" do hibernate.cfg.xml  para update

### ISSUE THREAD

**Issue by jjunio01** [ifpe-cti/saudegaranhuns#88]
Farei a referida alteração.

**Comment by fabriciofx** [comment]
@jjunio01 Por quê? Qual a razão dessa mudança?

**Comment by jjunio01** [comment]
@fabriciofx com o property "create" a cada vez que o arquivo hibernate.cfg.xml for executado será criado um novo banco, perdendo as informações já inseridas.

Com o property "update" serão atualizadas as informações existentes no banco e caso o banco ainda não exista o mesmo será criado.(Fazendo a mesma função do "create").

Com o "update" as informações guardadas não serão apagadas a cada execução do arquivo apenas serão atualizadas ou inseridas.

**Comment by fabriciofx** [comment]
@jjunio01 Concordo com a mudança.

**Comment by fabriciofx** [comment]
Closed by #89.
