### ISSUE TITLE
Adicionar "strategy" para geração dos ID's das entidades

### ISSUE THREAD

**Issue by FernandoSMedeiros** [ifpe-cti/saudegaranhuns#94]
Os ID's estão sendo gerados incorretamente, utilize a seguinte anotação nas entidades para corrigir o problema:

```
@GeneratedValue(strategy = GenerationType.IDENTITY)
```

@HeriklesVinicyus

**Comment by HeriklesVinicyus** [comment]
pode deixar!

**Comment by FernandoSMedeiros** [comment]
Ok.

**Comment by fabriciofx** [comment]
@FernandoSMedeiros Você fechou a issue, por quê? O PR de @HeriklesVinicyus ainda não entrou (merge).

**Comment by fabriciofx** [comment]
@FernandoSMedeiros Favor verificar se a mudança resolveu a issue.

**Comment by FernandoSMedeiros** [comment]
Ok
