### ISSUE TITLE
Corrigir propriedade das enumerações na páginas de consulta

### ISSUE THREAD

**Issue by jofernando** [ifpe-cti/saudegaranhuns#95]
Alterar propriedade `#{consultaController.prioridade.label}` por `#{consultaController.prioridade.nome}` em prioridade e nas demais enumerações utilizadas nessas páginas.

**Comment by jofernando** [comment]
Irei implementar isso.

**Comment by jofernando** [comment]
@fabriciofx atualizar tag para @jofernando

**Comment by fabriciofx** [comment]
@FernandoSMedeiros Só por curiosidade: vocês não conseguem alterar os labels das issues?

**Comment by fabriciofx** [comment]
Closed by #99.
